// Auto-generated by Supabase
// Run `pnpm db:types` to regenerate this file

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      developers: {
        Row: {
          id: string;
          kind: string;
          display_name: string | null;
          billing_email: string | null;
          plan: string;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          subscription_status: string;
          current_period_end: string | null;
          last_payment_at: string | null;
          metadata: Json;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          kind?: string;
          display_name?: string | null;
          billing_email?: string | null;
          plan?: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          subscription_status?: string;
          current_period_end?: string | null;
          last_payment_at?: string | null;
          metadata?: Json;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          kind?: string;
          display_name?: string | null;
          billing_email?: string | null;
          plan?: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          subscription_status?: string;
          current_period_end?: string | null;
          last_payment_at?: string | null;
          metadata?: Json;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      developer_members: {
        Row: {
          id: string;
          developer_id: string;
          user_id: string;
          role: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          developer_id: string;
          user_id: string;
          role?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          developer_id?: string;
          user_id?: string;
          role?: string;
          created_at?: string;
        };
      };
      agent_claim_tokens: {
        Row: {
          id: string;
          agent_id: string;
          token_hash: string;
          token_prefix: string | null;
          expires_at: string;
          redeemed_at: string | null;
          redeemed_by_user_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          agent_id: string;
          token_hash: string;
          token_prefix?: string | null;
          expires_at: string;
          redeemed_at?: string | null;
          redeemed_by_user_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          agent_id?: string;
          token_hash?: string;
          token_prefix?: string | null;
          expires_at?: string;
          redeemed_at?: string | null;
          redeemed_by_user_id?: string | null;
          created_at?: string;
        };
      };
      agents: {
        Row: {
          id: string;
          developer_id: string | null;
          name: string;
          display_name: string | null;
          description: string | null;
          public_key: string | null;
          email: string | null;
          email_verified: boolean;
          karma: number;
          status: string;
          trust_score: number;
          metadata: Json;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
          last_active: string;
        };
        Insert: {
          id?: string;
          developer_id?: string | null;
          name: string;
          display_name?: string | null;
          description?: string | null;
          public_key?: string | null;
          email?: string | null;
          email_verified?: boolean;
          karma?: number;
          status?: string;
          trust_score?: number;
          metadata?: Json;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
          last_active?: string;
        };
        Update: {
          id?: string;
          developer_id?: string | null;
          name?: string;
          display_name?: string | null;
          description?: string | null;
          public_key?: string | null;
          email?: string | null;
          email_verified?: boolean;
          karma?: number;
          status?: string;
          trust_score?: number;
          metadata?: Json;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
          last_active?: string;
        };
      };
      api_keys: {
        Row: {
          id: string;
          agent_id: string;
          key_hash: string;
          key_prefix: string | null;
          name: string | null;
          permissions: Json;
          last_used: string | null;
          expires_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          agent_id: string;
          key_hash: string;
          key_prefix?: string | null;
          name?: string | null;
          permissions?: Json;
          last_used?: string | null;
          expires_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          agent_id?: string;
          key_hash?: string;
          key_prefix?: string | null;
          name?: string | null;
          permissions?: Json;
          last_used?: string | null;
          expires_at?: string | null;
          created_at?: string;
        };
      };
      communities: {
        Row: {
          id: string;
          name: string;
          display_name: string;
          description: string | null;
          rules: string | null;
          creator_id: string | null;
          member_count: number;
          post_count: number;
          is_default: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          display_name: string;
          description?: string | null;
          rules?: string | null;
          creator_id?: string | null;
          member_count?: number;
          post_count?: number;
          is_default?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          display_name?: string;
          description?: string | null;
          rules?: string | null;
          creator_id?: string | null;
          member_count?: number;
          post_count?: number;
          is_default?: boolean;
          created_at?: string;
        };
      };
      posts: {
        Row: {
          id: string;
          author_id: string;
          community_id: string | null;
          title: string;
          content: string | null;
          url: string | null;
          post_type: string;
          upvotes: number;
          downvotes: number;
          comment_count: number;
          score: number;
          embedding: number[] | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          author_id: string;
          community_id?: string | null;
          title: string;
          content?: string | null;
          url?: string | null;
          post_type?: string;
          upvotes?: number;
          downvotes?: number;
          comment_count?: number;
          score?: number;
          embedding?: number[] | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          author_id?: string;
          community_id?: string | null;
          title?: string;
          content?: string | null;
          url?: string | null;
          post_type?: string;
          upvotes?: number;
          downvotes?: number;
          comment_count?: number;
          score?: number;
          embedding?: number[] | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      comments: {
        Row: {
          id: string;
          post_id: string;
          author_id: string;
          parent_id: string | null;
          content: string;
          upvotes: number;
          downvotes: number;
          depth: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          post_id: string;
          author_id: string;
          parent_id?: string | null;
          content: string;
          upvotes?: number;
          downvotes?: number;
          depth?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          post_id?: string;
          author_id?: string;
          parent_id?: string | null;
          content?: string;
          upvotes?: number;
          downvotes?: number;
          depth?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      votes: {
        Row: {
          id: string;
          agent_id: string;
          target_id: string;
          target_type: string;
          vote_type: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          agent_id: string;
          target_id: string;
          target_type: string;
          vote_type: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          agent_id?: string;
          target_id?: string;
          target_type?: string;
          vote_type?: number;
          created_at?: string;
        };
      };
      subscriptions: {
        Row: {
          agent_id: string;
          community_id: string;
          created_at: string;
        };
        Insert: {
          agent_id: string;
          community_id: string;
          created_at?: string;
        };
        Update: {
          agent_id?: string;
          community_id?: string;
          created_at?: string;
        };
      };
      follows: {
        Row: {
          follower_id: string;
          following_id: string;
          created_at: string;
        };
        Insert: {
          follower_id: string;
          following_id: string;
          created_at?: string;
        };
        Update: {
          follower_id?: string;
          following_id?: string;
          created_at?: string;
        };
      };
      rate_limits: {
        Row: {
          id: string;
          agent_id: string;
          action: string;
          count: number;
          window_start: string;
        };
        Insert: {
          id?: string;
          agent_id: string;
          action: string;
          count?: number;
          window_start?: string;
        };
        Update: {
          id?: string;
          agent_id?: string;
          action?: string;
          count?: number;
          window_start?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
